import type { Metadata } from "next";
import { Geist_Mono, Lato, Lexend } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/store/provider";
import TopBar from "@/components/layouts/Topbar";
import Header from "@/components/layouts/Header";
import Footer from "@/components/layouts/Footer";
import ThemeProvider from "@/components/ui/ThemeProvider";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lato = Lato({
  weight: ["300", "400", "700", "900"],
  subsets: ["latin"],
  variable: "--font-lato",
});

const lexend = Lexend({
  subsets: ["latin"],
  variable: "--font-lexend",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistMono.variable} ${lato.variable} ${lexend.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-[family-name:var(--font-lexend)]">
        <ThemeProvider>
          <ReduxProvider>
            {/* <TopBar /> */}
            <Header />
            {children}
            <Footer />
          </ReduxProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
