import type { Metadata } from "next";
import { Geist_Mono, Nunito } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/store/provider";
import Header from "@/components/layouts/Header";
import Footer from "@/components/layouts/Footer";
import AuthModal from "@/components/auth/AuthModal";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const nunito = Nunito({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-nunito",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Sierra Fish & Pets - Your One-Stop Shop for Quality Pet Supplies",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistMono.variable} ${nunito.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-[family-name:var(--font-nunito)]">
        <ReduxProvider>
          {/* <TopBar /> */}
          <Header />
          {children}
          <AuthModal />
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
